### PR TITLE
[WIP] Removed token dependencies

### PR DESCRIPTION
**Pull request by askolesov**

### CODE REVIEW

**Review by jovfer — APPROVED** [review]

**Comment by WadeBarnes** [comment]
(ci) test this please

**Comment by WadeBarnes** [comment]
(ci) test this please.

**Comment by WadeBarnes** [comment]
(ci) test this please

**Comment by WadeBarnes** [comment]
(ci) test this please

**Comment by WadeBarnes** [comment]
(ci) test this please

**Comment by WadeBarnes** [comment]
(ci) test this please

**Comment by WadeBarnes** [comment]
(ci) test this please

**Comment by askolesov** [comment]
Closing due inactivity

**Pull request closed without merging**
