### PR TITLE
Update current Apache 2.0 license to standard CCG license

### PR DESCRIPTION
**Pull request by vsnt**
Update this repo with the following standard license.

All Reports in this Repository are licensed by Contributors under the [W3C Software and Document
License](https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document).

Contributions to Specifications are made under the
[W3C CLA](https://www.w3.org/community/about/agreements/cla/).

Contributions to Software, including sample implementations, are under the
[Apache 2.0 License](https://www.apache.org/licenses/LICENSE-2.0).

### CODE REVIEW

**Review by WadeBarnes — CHANGES_REQUESTED** [review]
Hi @vsnt,  This PR appears to have a long list of unrelated changes in addition to a number of conflicts.  Perhaps your intended changes were not based on the most recent commits.  Could you please review.  You'll also need to amend sign-off to any commits that do not pass the DCO checks.

**Comment by vsnt** [comment]
@WadeBarnes my intention is to update the license agreement (https://github.com/w3c-ccg/sovrin/blob/master/LICENSE) of this repo (https://github.com/w3c-ccg/sovrin) with the standard CCG license boilerplate (https://github.com/w3c-ccg/community/issues/142#issuecomment-661296344). There was no way to create an issue for this particular repo, and the PR directed me to this... can you advise how to only make the change that is required for the sovrin repo in the CCG group?

**Comment by WadeBarnes** [comment]
@vsnt, It appears there have been a lot of changes to the [sovrin-foundation/sovrin](https://github.com/sovrin-foundation/sovrin) since the [w3c-ccg/sovrin](https://github.com/w3c-ccg/sovrin) was last synchronized with it.

You'll need to fetch or pull the latest from [sovrin-foundation/sovrin](https://github.com/sovrin-foundation/sovrin), and then update the affected files before submitting a PR.  That way the PR will only contain the intended changes.  There are several ways to manage that.  You could do it on a branch created in [w3c-ccg/sovrin](https://github.com/w3c-ccg/sovrin) or you could bring the main branch of [w3c-ccg/sovrin](https://github.com/w3c-ccg/sovrin) up date with [sovrin-foundation/sovrin](https://github.com/sovrin-foundation/sovrin).

**Comment by vsnt** [comment]
Heya @kimdhamilton & @wyc can you please take a look and advise on resolving? Thanks.

**Comment by wyc** [comment]
Hi all, thanks for the comments. This PR has stemmed from an effort to resolve this issue within the W3C Credentials Community Group: https://github.com/w3c-ccg/community/issues/142

The Sovrin repository seems to have been mirrored to https://github.com/w3c-ccg/sovrin some time ago, and as @WadeBarnes has suggested, the CCG mirror is very behind the current repository. I also do not believe Sovrin to be an official work item of the CCG, but perhaps just a mirror for purposes of which I'm unaware.

Because the Sovrin project is not a CCG work item with owners and contributors, I suggest we keep it as a simple mirror of this repository, and not attempt to change it to W3C-friendly licensing, as that decision is for the Sovrin Foundation and not the CCG. So we should:
- Close this PR
- `git pull --ff-only` from `sovrin-foundation/sovrin` to `w3c-ccg/sovrin` and update the branch there.

Does that sound okay to everyone?

**Comment by vsnt** [comment]
Thanks @wyc. Do we need to keep this repo in the CCG directory moving forward? Can we not delete it and move forward since it isn't an official work item? @msporny any historical insight?

**Comment by wyc** [comment]
@vsnt to avoid superfluous notifications to this repo's subscribers, we can probably close this PR and discuss the future state of the CCG repo in a new issue under w3c-ccg/community.

**Pull request closed without merging**
